<?php require_once ("elements/menu.html"); ?>
<fieldset>
    <legend>Formulário de contato</legend>
    <div class="form-group row">
        <label for="example-text-input" class="col-xs-2 col-form-label">Text</label>
        <div class="col-xs-10">
            <input class="form-control" type="text" value="" id="example-text-input">
        </div>
    </div>
    <div class="form-group row">
        <label for="example-email-input" class="col-xs-2 col-form-label">Email</label>
        <div class="col-xs-10">
            <input class="form-control" type="email" value="" id="example-email-input">
        </div>
    </div>
    <div class="form-group row">
        <label for="example-tel-input" class="col-xs-2 col-form-label">Telefone</label>
        <div class="col-xs-10">
            <input class="form-control" type="tel" value="" id="example-tel-input">
        </div>
    </div>
    <button type="button" class="btn btn-success">Enviar</button>
</fieldset>

<?php require_once ("elements/rodape.html"); ?>

