<?php require_once ("elements/menu.html"); ?>
<section id="banner" class="container">
    <figure>
        <img class="img-responsive" src="./img/banner.png" alt=""></img>
    </figure>
</section>
<br />
<section id="escolha" class="container">
    <article class="col-lg-4 col-lg-offset-1 col-md-6 col-sm-6 col-xs-12">
        <figure class="center-block">
            <img src="./img/food-truck-site.png" class="img-responsive" alt="">
            <caption>Precisa de um espaço para Food Truck?</caption>
        </figure>
    </article>
    <article class="col-lg-4 col-lg-offset-2 col-md-6 col-sm-6 col-xs-12">
        <figure class="center-block">
            <img src="./img/food-truck-site.png" class="img-responsive" alt="">
            <caption>Precisa de um Food Truck para seu espaço?</caption>
        </figure>
    </article>
</section>
<section id="quemSomos" class="container sectionsGeral">
    <h2>Quem Somos</h2>
    <p>Você tem um Food Truck mas não tem um espaço para trabalhar? Você tem um espaço e quer alugar? O Espaço Truck faz o meio de campo entre o Food Truck e o Espaço para aluguel. Através de uma busca simples, você encontra o lugar ideal para trabalhar.</p>
</section>

<section id="missao" class="container sectionsGeral">
    <h2>Missão</h2>
    <p>Nossa missão é unir os donos de Food Truck e os donos de espaços para eventos e comércio. Diminuir a distância e facilitar a negociação para que todos possam ganhar.</p>
</section>

<?php require_once ("elements/rodape.html"); ?>
