<?php require_once ("elements/menu.html"); ?>

    <section id="quemSomos" class="container sectionsGeral">
        <h2>Quem Somos</h2>
        <p>Você tem um Food Truck mas não tem um espaço para trabalhar? Você tem um espaço e quer alugar? O Espaço Truck faz o meio de campo entre o Food Truck e o Espaço para aluguel. Através de uma busca simples, você encontra o lugar ideal para trabalhar.</p>
    </section>

<?php require_once ("elements/rodape.html"); ?>